TRUNCATE `{prefix}_board_q`;
TRUNCATE `{prefix}_board_r`;
TRUNCATE `{prefix}_category`;
TRUNCATE `{prefix}_comment`;
TRUNCATE `{prefix}_index`;
TRUNCATE `{prefix}_index_detail`;
TRUNCATE `{prefix}_menus`;
TRUNCATE `{prefix}_modules`;
INSERT INTO `{prefix}_category` (`id`, `module_id`, `category_id`, `group_id`, `language`, `topic`, `detail`, `icon`, `icon_w`, `icon_h`, `config`, `c1`, `c2`, `published`, `subcategory`) VALUES ('1','10','1','0','','a:1:{s:0:"";s:3:"MEN";}','','','0','0','','0','0','1','a:4:{i:1;a:1:{s:2:"th";s:10:"What\'s Hot";}i:2;a:1:{s:2:"th";s:21:"Suiting &amp; Blazers";}i:3;a:1:{s:2:"th";s:10:"Shirt Shop";}i:4;a:1:{s:2:"th";s:15:"Tees &amp; Polo";}}');
INSERT INTO `{prefix}_category` (`id`, `module_id`, `category_id`, `group_id`, `language`, `topic`, `detail`, `icon`, `icon_w`, `icon_h`, `config`, `c1`, `c2`, `published`, `subcategory`) VALUES ('2','10','2','0','','a:1:{s:0:"";s:5:"WOMEN";}','','','0','0','','0','0','1','a:4:{i:1;a:1:{s:2:"th";s:10:"What\'s Hot";}i:2;a:1:{s:2:"th";s:5:"Dress";}i:3;a:1:{s:2:"th";s:5:"Skirt";}i:4;a:1:{s:2:"th";s:4:"Shoe";}}');
INSERT INTO `{prefix}_category` (`id`, `module_id`, `category_id`, `group_id`, `language`, `topic`, `detail`, `icon`, `icon_w`, `icon_h`, `config`, `c1`, `c2`, `published`, `subcategory`) VALUES ('3','10','3','0','','a:1:{s:0:"";s:5:"JEANS";}','','','0','0','','0','0','1','a:2:{i:1;a:1:{s:2:"th";s:11:"Men\'s Jeans";}i:2;a:1:{s:2:"th";s:13:"Women\'s Jeans";}}');
INSERT INTO `{prefix}_category` (`id`, `module_id`, `category_id`, `group_id`, `language`, `topic`, `detail`, `icon`, `icon_w`, `icon_h`, `config`, `c1`, `c2`, `published`, `subcategory`) VALUES ('4','10','4','0','','a:1:{s:0:"";s:5:"SALES";}','','','0','0','','0','0','1','a:2:{i:1;a:1:{s:2:"th";s:15:"Men\'s Clearance";}i:2;a:1:{s:2:"th";s:17:"Women\'s Clearance";}}');
INSERT INTO `{prefix}_index` (`id`, `index`, `module_id`, `category_id`, `language`, `sender`, `member_id`, `email`, `ip`, `create_date`, `last_update`, `visited`, `comments`, `comment_id`, `commentator`, `commentator_id`, `comment_date`, `picture`, `pictureW`, `pictureH`, `hassubpic`, `can_reply`, `published`, `pin`, `locked`, `related`, `published_date`, `alias`) VALUES ('1','1','1','0','','','1','','110.168.19.114','0','1524821354','3027','0','0','','0','0','','0','0','0','0','1','1','1','','2013-06-22','GCMS Ajax CMS');
INSERT INTO `{prefix}_index` (`id`, `index`, `module_id`, `category_id`, `language`, `sender`, `member_id`, `email`, `ip`, `create_date`, `last_update`, `visited`, `comments`, `comment_id`, `commentator`, `commentator_id`, `comment_date`, `picture`, `pictureW`, `pictureH`, `hassubpic`, `can_reply`, `published`, `pin`, `locked`, `related`, `published_date`, `alias`) VALUES ('2','1','2','0','','','1','','49.48.206.73','0','1367724891','158','0','0','','0','0','','0','0','0','0','1','0','0','','2013-06-22','เกี่ยวกับเรา - ติดต่อเรา');
INSERT INTO `{prefix}_index` (`id`, `index`, `module_id`, `category_id`, `language`, `sender`, `member_id`, `email`, `ip`, `create_date`, `last_update`, `visited`, `comments`, `comment_id`, `commentator`, `commentator_id`, `comment_date`, `picture`, `pictureW`, `pictureH`, `hassubpic`, `can_reply`, `published`, `pin`, `locked`, `related`, `published_date`, `alias`) VALUES ('3','1','3','0','','','0','','','0','0','0','0','0','','0','0','','0','0','0','0','1','0','0','','2013-06-22','บทความ แหล่งเรียนรู้ :: Knowledge');
INSERT INTO `{prefix}_index` (`id`, `index`, `module_id`, `category_id`, `language`, `sender`, `member_id`, `email`, `ip`, `create_date`, `last_update`, `visited`, `comments`, `comment_id`, `commentator`, `commentator_id`, `comment_date`, `picture`, `pictureW`, `pictureH`, `hassubpic`, `can_reply`, `published`, `pin`, `locked`, `related`, `published_date`, `alias`) VALUES ('4','1','4','0','','','0','','','0','0','1','0','0','','0','0','','0','0','0','0','1','0','0','','2013-06-22','GCMS บอร์ด');
INSERT INTO `{prefix}_index` (`id`, `index`, `module_id`, `category_id`, `language`, `sender`, `member_id`, `email`, `ip`, `create_date`, `last_update`, `visited`, `comments`, `comment_id`, `commentator`, `commentator_id`, `comment_date`, `picture`, `pictureW`, `pictureH`, `hassubpic`, `can_reply`, `published`, `pin`, `locked`, `related`, `published_date`, `alias`) VALUES ('5','0','3','1','','','1','','171.5.251.149','1379217826','1390276091','34','0','0','','0','0','','0','0','0','0','1','0','0','','2013-09-15','บทความแรกของคุณ');
INSERT INTO `{prefix}_index` (`id`, `index`, `module_id`, `category_id`, `language`, `sender`, `member_id`, `email`, `ip`, `create_date`, `last_update`, `visited`, `comments`, `comment_id`, `commentator`, `commentator_id`, `comment_date`, `picture`, `pictureW`, `pictureH`, `hassubpic`, `can_reply`, `published`, `pin`, `locked`, `related`, `published_date`, `alias`) VALUES ('6','0','3','2','','','1','','171.5.250.37','1379217882','1379217882','39','1','1','admin@goragod.com','1','1379217942','','0','0','0','1','1','0','0','','2013-09-15','ข่าวแรกของคุณ');
INSERT INTO `{prefix}_index` (`id`, `index`, `module_id`, `category_id`, `language`, `sender`, `member_id`, `email`, `ip`, `create_date`, `last_update`, `visited`, `comments`, `comment_id`, `commentator`, `commentator_id`, `comment_date`, `picture`, `pictureW`, `pictureH`, `hassubpic`, `can_reply`, `published`, `pin`, `locked`, `related`, `published_date`, `alias`) VALUES ('7','1','8','0','','','0','','','0','0','0','0','0','','0','0','','0','0','0','0','1','0','0','','0000-00-00','');
INSERT INTO `{prefix}_index` (`id`, `index`, `module_id`, `category_id`, `language`, `sender`, `member_id`, `email`, `ip`, `create_date`, `last_update`, `visited`, `comments`, `comment_id`, `commentator`, `commentator_id`, `comment_date`, `picture`, `pictureW`, `pictureH`, `hassubpic`, `can_reply`, `published`, `pin`, `locked`, `related`, `published_date`, `alias`) VALUES ('8','1','5','0','','','0','','','0','0','0','0','0','','0','0','','0','0','0','0','1','0','0','','0000-00-00','');
INSERT INTO `{prefix}_index` (`id`, `index`, `module_id`, `category_id`, `language`, `sender`, `member_id`, `email`, `ip`, `create_date`, `last_update`, `visited`, `comments`, `comment_id`, `commentator`, `commentator_id`, `comment_date`, `picture`, `pictureW`, `pictureH`, `hassubpic`, `can_reply`, `published`, `pin`, `locked`, `related`, `published_date`, `alias`) VALUES ('9','1','6','0','','','0','','','0','0','0','0','0','','0','0','','0','0','0','0','1','0','0','','0000-00-00','');
INSERT INTO `{prefix}_index` (`id`, `index`, `module_id`, `category_id`, `language`, `sender`, `member_id`, `email`, `ip`, `create_date`, `last_update`, `visited`, `comments`, `comment_id`, `commentator`, `commentator_id`, `comment_date`, `picture`, `pictureW`, `pictureH`, `hassubpic`, `can_reply`, `published`, `pin`, `locked`, `related`, `published_date`, `alias`) VALUES ('11','1','8','0','','','0','','','0','0','0','0','0','','0','0','','0','0','0','0','1','0','0','','0000-00-00','');
INSERT INTO `{prefix}_index` (`id`, `index`, `module_id`, `category_id`, `language`, `sender`, `member_id`, `email`, `ip`, `create_date`, `last_update`, `visited`, `comments`, `comment_id`, `commentator`, `commentator_id`, `comment_date`, `picture`, `pictureW`, `pictureH`, `hassubpic`, `can_reply`, `published`, `pin`, `locked`, `related`, `published_date`, `alias`) VALUES ('12','1','9','0','','','0','','','0','0','0','0','0','','0','0','','0','0','0','0','1','0','0','','0000-00-00','');
INSERT INTO `{prefix}_index` (`id`, `index`, `module_id`, `category_id`, `language`, `sender`, `member_id`, `email`, `ip`, `create_date`, `last_update`, `visited`, `comments`, `comment_id`, `commentator`, `commentator_id`, `comment_date`, `picture`, `pictureW`, `pictureH`, `hassubpic`, `can_reply`, `published`, `pin`, `locked`, `related`, `published_date`, `alias`) VALUES ('13','1','10','0','','','0','','','0','0','0','0','0','','0','0','','0','0','0','0','1','0','0','','0000-00-00','');
INSERT INTO `{prefix}_index_detail` (`id`, `module_id`, `language`, `topic`, `description`, `detail`, `keywords`, `relate`) VALUES ('2','2','','เกี่ยวกับเรา - ติดต่อเรา','เกี่ยวกับเรา ติดต่อเรา About Us','{WIDGET_CONTACT_admin@demo.com}','เกี่ยวกับเรา ติดต่อเรา About Us','');
INSERT INTO `{prefix}_index_detail` (`id`, `module_id`, `language`, `topic`, `description`, `detail`, `keywords`, `relate`) VALUES ('3','3','','บทความ แหล่งเรียนรู้ :: Knowledge','บทความ แหล่งเรียนรู้ Knowledge goragod.com','','บทความ แหล่งเรียนรู้ Knowledge goragod.com','');
INSERT INTO `{prefix}_index_detail` (`id`, `module_id`, `language`, `topic`, `description`, `detail`, `keywords`, `relate`) VALUES ('4','4','','GCMS บอร์ด','เว็บบอร์ด GCMS Board ถามตอปัญหาคาใจ www.gcms.in.th','','เว็บบอร์ด GCMS Board ถามตอปัญหาคาใจ www.gcms.in.th','');
INSERT INTO `{prefix}_index_detail` (`id`, `module_id`, `language`, `topic`, `description`, `detail`, `keywords`, `relate`) VALUES ('5','3','','บทความแรกของคุณ','นี่คือบทความแรกของคุณ คุณ สามารถ ลบ หรือ แก้ไขมันได้','นี่คือบทความแรกของคุณ คุณ สามารถ ลบ หรือ แก้ไขมันได้','บทความแรกของคุณ','');
INSERT INTO `{prefix}_index_detail` (`id`, `module_id`, `language`, `topic`, `description`, `detail`, `keywords`, `relate`) VALUES ('6','3','','ข่าวแรกของคุณ','นี่คือข่าวแรกของคุณ คุณสามารถ ลบ หรือ แก้ไขได้','นี่คือข่าวแรกของคุณ คุณสามารถ ลบ หรือ แก้ไขได้','ข่าวแรกของคุณ','');
INSERT INTO `{prefix}_index_detail` (`id`, `module_id`, `language`, `topic`, `description`, `detail`, `keywords`, `relate`) VALUES ('7','3','','ทดสอบครับ','ทดสอบครับ ทดสอบครับ','ทดสอบครับ ทดสอบครับ','ทดสอบครับ','');
INSERT INTO `{prefix}_index_detail` (`id`, `module_id`, `language`, `topic`, `description`, `detail`, `keywords`, `relate`) VALUES ('8','5','','Download','','','','');
INSERT INTO `{prefix}_index_detail` (`id`, `module_id`, `language`, `topic`, `description`, `detail`, `keywords`, `relate`) VALUES ('9','6','','Gallery','','','','');
INSERT INTO `{prefix}_index_detail` (`id`, `module_id`, `language`, `topic`, `description`, `detail`, `keywords`, `relate`) VALUES ('11','8','','Video','','','','');
INSERT INTO `{prefix}_index_detail` (`id`, `module_id`, `language`, `topic`, `description`, `detail`, `keywords`, `relate`) VALUES ('12','9','','Payment','','','','');
INSERT INTO `{prefix}_index_detail` (`id`, `module_id`, `language`, `topic`, `description`, `detail`, `keywords`, `relate`) VALUES ('13','10','','Product','','','','');
INSERT INTO `{prefix}_index_detail` (`id`, `module_id`, `language`, `topic`, `description`, `detail`, `keywords`, `relate`) VALUES ('1','1','','ตัวอย่างระบบซื้อขายสินค้าและตะกร้าสินค้า','ตัวอย่างระบบซื้อขายสินค้าและตะกร้าสินค้า สร้างจาก GCMS','<h1>ยินดีต้อนรับสู่ GCMS</h1>\r\n\r\n<div>\r\n<p style="margin-bottom: 10px;">ขณะนี้คุณได้ติดตั้ง GCMS เป็นที่เรียบร้อยแล้ว และนี่คือหน้าแรกของคุณ</p>\r\n\r\n<p style="margin-bottom: 10px;">GCMS เป็น Ajax CMS สมบูรณ์แบบ ที่พัฒนาโดยคนไทยทั้งระบบ เพื่อให้การใช้งาน CMS แบบ Ajax เป็นเรื่องที่ง่ายขึ้น และแก้ปัญหาของ Ajax ที่เป็นที่กังวล ทั้งในเรื่องการรองรับหลายบราวเซอร์, การปิดการใช้งาน Javascript, การ Refresh หน้า, การ Bookmark, การใช้งานปุ่ม History ของบราวเซอร์ และที่สำคัญคือ SEO</p>\r\n\r\n<p style="margin-bottom: 10px;">GCMS เหมาะสมสำหรับการทำเว็บไซต์ทั่วไป ทั้งเว็บไซต์ส่วนบุคคล หน่วยงานราชการ หรือเว็บไซต์อื่นๆ ตั้งแต่ขนาดเล็ก ไปจนถึงเว็บไซต์ขนาดใหญ่ ด้วยการออกแบบที่เน้นอิสระในการปรับปรุงหน้าเว็บ ไม่มุ่งเน้นไปที่เว็บไซต์แบบใดแบบหนึ่งโดยเฉพาะ และมีคุณสมบัติเบื้องต้นต่อการออกแบบเว็บไซต์ทั่วไปได้ง่าย นอกจากนี้ GCMS ยังเหมาะสมเป็นอย่างยิ่ง สำหรับผู้ที่ชอบออกแบบเว็บด้วยตัวเอง ด้วยการใช้ GCMS เป็นพื้นฐานของเว็บเนื่องจาก GCMS มีระบบพื้นฐานครบถ้วน และออกแบบโมดูลตามความต้องการเพื่อใช้งานร่วมกับ GCMS ซึ่งทำให้ประหยัดเวลาในการออกแบบเว็บลงเป็นอย่างมาก</p>\r\n\r\n<p style="margin-bottom: 10px;">หากคุณมีข้อสงสัย ข้อเสนอแนะ หรือต้องการความช่วยเหลือเกี่ยวกับ GCMS คุณสามารถหาความช่วยเหลือนั้นได้ที่ <a href="http://www.goragod.com" rel="nofollow">http://www.goragod.com</a> และคุณสามารถแสดงความคิดเห็นของคุณต่อ GCMS รวมถึงปัญหาในการใช้งาน ตลอดจนข้อผิดพลาดต่างๆ ของ GCMS ได้ ความคิดเห็นของคุณจะช่วยผมในการพัฒนา GCMS ให้ดียิ่งขึ้นในโอกาศต่อไป</p>\r\n\r\n<p style="text-align: right; margin-bottom: 10px;">ด้วยความขอบคุณ<br>\r\n<strong>กรกฎ วิริยะ</strong></p>\r\n\r\n<p style="margin-bottom: 10px; font-weight: bold;">ข้อตกลงการนำ GCMS ไปใช้งาน</p>\r\n\r\n<ul style="padding: 0px 0px 0px 40px;">\r\n	<li>GCMS เป็น Ajax CMS ชนิด Open Source ที่แจกจ่ายให้กับทุกคนสามารถนำไปใช้งานได้ ฟรี โดยมีเงื่อนไขว่า <strong>ต้องติดข้อความหรือเครื่องหมายของผู้พัฒนาไว้เสมอ </strong>(http://www.goragod.com)</li>\r\n	<li>ห้ามนำ GCMS หรือ ส่วนหนึ่งส่วนใดของ GCMS ไป จำหน่าย จ่าย แจก หรือ ใช้งานกับบุคคลที่สาม เว้นแต่จะได้รับความยินยอมจากผู้พัฒนา</li>\r\n	<li>คุณสามารถพัฒนาต่อยอด เพิ่มเติม แก้ไข หรือ ดัดแปลง GCMS ได้เพื่อการใช้งานส่วนบุคคล โดยต้องติดข้อความหรือโลโกของผู้พัฒนาไว้เสมอไม่ว่าจะเปลี่ยนแปลงไปมากน้อยแค่ไหนก็ตาม</li>\r\n	<li>คุณสามารถพัฒนา โมดูลเสริม หรือ วิดเจ็ท หรือ ส่วนประกอบอื่นใด (นอกจากที่มีแจกจ่ายโดยผู้พัฒนาอยู่แล้ว) เพื่อใช้หรือเพื่อจำหน่าย จ่าย แจกได้ โดยให้สิทธิ์เป็นของผู้พัฒนาเอง (ขายหรือแจกเฉพาะโมดูล)</li>\r\n	<li>หากคุณต้องการนำ GCMS ไปใช้กับบุคลที่สาม หรือ เพื่อขาย หรือต้องการนำเครื่องหมายหรือข้อความของผู้พัฒนาออก คุณสามารถติดต่อกับผู้พัฒนาได้โดยตรง ตามที่อยู่ใน <a href="http://www.goragod.com/about.html" rel="nofollow">http://www.goragod.com/about.html</a></li>\r\n</ul>\r\n</div>\r\n','ตัวอย่างระบบซื้อขายสินค้าและตะกร้าสินค้า สร้างจาก GCMS','');
INSERT INTO `{prefix}_menus` (`id`, `index_id`, `parent`, `level`, `language`, `menu_text`, `menu_tooltip`, `accesskey`, `menu_order`, `menu_url`, `menu_target`, `alias`, `published`) VALUES ('1','1','MAINMENU','0','','หน้าหลัก','หน้าหลัก :: Home','','1','','','','0');
INSERT INTO `{prefix}_menus` (`id`, `index_id`, `parent`, `level`, `language`, `menu_text`, `menu_tooltip`, `accesskey`, `menu_order`, `menu_url`, `menu_target`, `alias`, `published`) VALUES ('4','0','BOTTOMMENU','0','','Member','เมนูสมาชิก :: Member','','2','?module=dologin','','logout','2');
INSERT INTO `{prefix}_menus` (`id`, `index_id`, `parent`, `level`, `language`, `menu_text`, `menu_tooltip`, `accesskey`, `menu_order`, `menu_url`, `menu_target`, `alias`, `published`) VALUES ('5','0','BOTTOMMENU','0','','Log in','เข้าระบบ :: Log in','','3','?module=dologin','','dologin','3');
INSERT INTO `{prefix}_menus` (`id`, `index_id`, `parent`, `level`, `language`, `menu_text`, `menu_tooltip`, `accesskey`, `menu_order`, `menu_url`, `menu_target`, `alias`, `published`) VALUES ('6','12','BOTTOMMENU','0','','Payment','ชำระเงิน :: Payment','','1','','','','1');
INSERT INTO `{prefix}_modules` (`id`, `owner`, `module`, `config`) VALUES ('1','index','home','');
INSERT INTO `{prefix}_modules` (`id`, `owner`, `module`, `config`) VALUES ('2','index','about','');
INSERT INTO `{prefix}_modules` (`id`, `owner`, `module`, `config`) VALUES ('3','document','knowledge','icon_w=32\nicon_h=32\ndefault_icon=modules/document/img/document-icon.png\nicon_width=75\nicon_height=75\nimg_typies=jpg\nlist_per_page=20\ncan_view=-1,0,2,1\nviewing=0\nnew_date=604800\nmoderator=2,1\ncan_reply=0,1,2\nnews_count=15\nnews_sort=0\npublished=1\nsort=0\ncan_config=1\ncan_write=2,1');
INSERT INTO `{prefix}_modules` (`id`, `owner`, `module`, `config`) VALUES ('4','board','forum','icon_w=32\nicon_h=32\ndefault_icon=modules/board/img/board-icon.png\nicon_width=32\nicon_height=32\nicon_category_type=jpg,gif,png\nlist_per_page=20\ncan_view=0,2,1\nviewing=1\nnew_date=604800\nnews_date=604800\nmoderator=2,1\ncan_config=1\ncan_reply=0,2,1\nimg_upload_size=500\nimg_law=0\nthumb_width=16\nimg_upload_type=jpg\ncan_post=0,2,1');
INSERT INTO `{prefix}_modules` (`id`, `owner`, `module`, `config`) VALUES ('5','download','download','');
INSERT INTO `{prefix}_modules` (`id`, `owner`, `module`, `config`) VALUES ('6','gallery','gallery','');
INSERT INTO `{prefix}_modules` (`id`, `owner`, `module`, `config`) VALUES ('8','video','video','');
INSERT INTO `{prefix}_modules` (`id`, `owner`, `module`, `config`) VALUES ('9','payment','payment','');
INSERT INTO `{prefix}_modules` (`id`, `owner`, `module`, `config`) VALUES ('10','product','product','');
INSERT INTO `{prefix}_product` (`id`, `module_id`, `product_no`, `alias`, `published`, `can_reply`, `last_update`, `visited`, `comments`, `quantity`, `unit`, `new`, `hot`, `recommend`, `category`) VALUES ('1','10','P0001','off_the_shoulder_sheath_dress','1','0','1524755107','5','0','0','0','0','0','1','');
INSERT INTO `{prefix}_product` (`id`, `module_id`, `product_no`, `alias`, `published`, `can_reply`, `last_update`, `visited`, `comments`, `quantity`, `unit`, `new`, `hot`, `recommend`, `category`) VALUES ('2','10','P0002','solid_off_the_shoulder_ruffle_fit_and_flare_dress','1','0','1524755419','7','0','0','0','1','0','0','');
INSERT INTO `{prefix}_product` (`id`, `module_id`, `product_no`, `alias`, `published`, `can_reply`, `last_update`, `visited`, `comments`, `quantity`, `unit`, `new`, `hot`, `recommend`, `category`) VALUES ('3','10','P0003','off_the_shoulder_smocked_eyelet_mini_dress','1','0','1524756461','6','0','0','0','0','1','0','');
INSERT INTO `{prefix}_product` (`id`, `module_id`, `product_no`, `alias`, `published`, `can_reply`, `last_update`, `visited`, `comments`, `quantity`, `unit`, `new`, `hot`, `recommend`, `category`) VALUES ('4','10','P0004','off_the_shoulder_floral_embroidered_shift_dress','1','0','1524756562','13','0','0','0','0','0','1','');
INSERT INTO `{prefix}_product` (`id`, `module_id`, `product_no`, `alias`, `published`, `can_reply`, `last_update`, `visited`, `comments`, `quantity`, `unit`, `new`, `hot`, `recommend`, `category`) VALUES ('5','10','P0005','ikat_print_crew_neck_tee','1','0','1524790743','9','0','0','0','1','1','0','');
INSERT INTO `{prefix}_product` (`id`, `module_id`, `product_no`, `alias`, `published`, `can_reply`, `last_update`, `visited`, `comments`, `quantity`, `unit`, `new`, `hot`, `recommend`, `category`) VALUES ('6','10','P0006','jersey_scoop_neck_pocket_tank','1','0','1524790884','0','0','0','0','0','1','0','');
INSERT INTO `{prefix}_product` (`id`, `module_id`, `product_no`, `alias`, `published`, `can_reply`, `last_update`, `visited`, `comments`, `quantity`, `unit`, `new`, `hot`, `recommend`, `category`) VALUES ('7','10','P0007','slim_charcoal_gray_check_stretch_wool_blend_suit_vest','1','0','1524791717','4','0','0','0','0','0','1','');
INSERT INTO `{prefix}_product` (`id`, `module_id`, `product_no`, `alias`, `published`, `can_reply`, `last_update`, `visited`, `comments`, `quantity`, `unit`, `new`, `hot`, `recommend`, `category`) VALUES ('8','10','P0008','color_block_crew_neck_tee','1','0','1524791891','19','0','0','0','1','0','0','');
INSERT INTO `{prefix}_product` (`id`, `module_id`, `product_no`, `alias`, `published`, `can_reply`, `last_update`, `visited`, `comments`, `quantity`, `unit`, `new`, `hot`, `recommend`, `category`) VALUES ('9','10','P0009','color_block_raglan_henley_sweater','1','0','1524792342','33','0','0','0','0','1','0','');
INSERT INTO `{prefix}_product` (`id`, `module_id`, `product_no`, `alias`, `published`, `can_reply`, `last_update`, `visited`, `comments`, `quantity`, `unit`, `new`, `hot`, `recommend`, `category`) VALUES ('10','10','P0010','striped_notch_neck_henley','1','0','1524792573','36','0','0','0','0','0','1','');
INSERT INTO `{prefix}_product` (`id`, `module_id`, `product_no`, `alias`, `published`, `can_reply`, `last_update`, `visited`, `comments`, `quantity`, `unit`, `new`, `hot`, `recommend`, `category`) VALUES ('11','10','P0011','merino_wool_blend_thermal_regulating_v_neck_sweater','1','0','1524793331','31','0','0','0','1','0','0','');
INSERT INTO `{prefix}_product` (`id`, `module_id`, `product_no`, `alias`, `published`, `can_reply`, `last_update`, `visited`, `comments`, `quantity`, `unit`, `new`, `hot`, `recommend`, `category`) VALUES ('12','10','P0012','marled_funnel_neck_pullover_sweater','1','0','1524793314','29','0','0','0','0','0','1','');
INSERT INTO `{prefix}_product_additional` (`id`, `module_id`, `product_id`, `topic`, `price_THB`, `net_THB`, `price_USD`, `net_USD`, `weight`, `stock`) VALUES ('0','10','1','Diva Red 528','490','290','49','29','0','-1');
INSERT INTO `{prefix}_product_additional` (`id`, `module_id`, `product_id`, `topic`, `price_THB`, `net_THB`, `price_USD`, `net_USD`, `weight`, `stock`) VALUES ('1','10','1','Pitch Black 58','490','290','49','29','0','-1');
INSERT INTO `{prefix}_product_additional` (`id`, `module_id`, `product_id`, `topic`, `price_THB`, `net_THB`, `price_USD`, `net_USD`, `weight`, `stock`) VALUES ('0','10','2','Red 2167','0','590','0','59','0','-1');
INSERT INTO `{prefix}_product_additional` (`id`, `module_id`, `product_id`, `topic`, `price_THB`, `net_THB`, `price_USD`, `net_USD`, `weight`, `stock`) VALUES ('0','10','4','Chambray Wash 1788','0','690','0','69','0','-1');
INSERT INTO `{prefix}_product_additional` (`id`, `module_id`, `product_id`, `topic`, `price_THB`, `net_THB`, `price_USD`, `net_USD`, `weight`, `stock`) VALUES ('0','10','3','True White 1','0','690','0','69','0','-1');
INSERT INTO `{prefix}_product_additional` (`id`, `module_id`, `product_id`, `topic`, `price_THB`, `net_THB`, `price_USD`, `net_USD`, `weight`, `stock`) VALUES ('0','10','5','Blue 1413','0','340','0','34','0','-1');
INSERT INTO `{prefix}_product_additional` (`id`, `module_id`, `product_id`, `topic`, `price_THB`, `net_THB`, `price_USD`, `net_USD`, `weight`, `stock`) VALUES ('0','10','6','Bright Blue 200','0','290','0','29','0','-1');
INSERT INTO `{prefix}_product_additional` (`id`, `module_id`, `product_id`, `topic`, `price_THB`, `net_THB`, `price_USD`, `net_USD`, `weight`, `stock`) VALUES ('1','10','6','Blue 1737','0','290','0','29','0','-1');
INSERT INTO `{prefix}_product_additional` (`id`, `module_id`, `product_id`, `topic`, `price_THB`, `net_THB`, `price_USD`, `net_USD`, `weight`, `stock`) VALUES ('0','10','7','Charcoal 904','0','980','0','98','0','-1');
INSERT INTO `{prefix}_product_additional` (`id`, `module_id`, `product_id`, `topic`, `price_THB`, `net_THB`, `price_USD`, `net_USD`, `weight`, `stock`) VALUES ('0','10','8','Yellow 1116','0','340','0','34','0','-1');
INSERT INTO `{prefix}_product_additional` (`id`, `module_id`, `product_id`, `topic`, `price_THB`, `net_THB`, `price_USD`, `net_USD`, `weight`, `stock`) VALUES ('1','10','8','Teal 2131','0','340','0','34','0','-1');
INSERT INTO `{prefix}_product_additional` (`id`, `module_id`, `product_id`, `topic`, `price_THB`, `net_THB`, `price_USD`, `net_USD`, `weight`, `stock`) VALUES ('0','10','9','Glacier 623','590','400','0','0','0','-1');
INSERT INTO `{prefix}_product_additional` (`id`, `module_id`, `product_id`, `topic`, `price_THB`, `net_THB`, `price_USD`, `net_USD`, `weight`, `stock`) VALUES ('1','10','9','Navy 1981','590','400','0','0','0','-1');
INSERT INTO `{prefix}_product_additional` (`id`, `module_id`, `product_id`, `topic`, `price_THB`, `net_THB`, `price_USD`, `net_USD`, `weight`, `stock`) VALUES ('2','10','9','Black 58','590','400','0','0','0','-1');
INSERT INTO `{prefix}_product_additional` (`id`, `module_id`, `product_id`, `topic`, `price_THB`, `net_THB`, `price_USD`, `net_USD`, `weight`, `stock`) VALUES ('0','10','10','Blue 925','490','290','0','0','0','-1');
INSERT INTO `{prefix}_product_additional` (`id`, `module_id`, `product_id`, `topic`, `price_THB`, `net_THB`, `price_USD`, `net_USD`, `weight`, `stock`) VALUES ('1','10','10','Black 58','490','290','0','0','0','-1');
INSERT INTO `{prefix}_product_additional` (`id`, `module_id`, `product_id`, `topic`, `price_THB`, `net_THB`, `price_USD`, `net_USD`, `weight`, `stock`) VALUES ('2','10','10','Red 373','490','290','0','0','0','-1');
INSERT INTO `{prefix}_product_additional` (`id`, `module_id`, `product_id`, `topic`, `price_THB`, `net_THB`, `price_USD`, `net_USD`, `weight`, `stock`) VALUES ('1','10','12','Red 1281','790','590','0','0','0','-1');
INSERT INTO `{prefix}_product_additional` (`id`, `module_id`, `product_id`, `topic`, `price_THB`, `net_THB`, `price_USD`, `net_USD`, `weight`, `stock`) VALUES ('1','10','11','Ruby Red 1281','790','590','0','0','0','-1');
INSERT INTO `{prefix}_product_additional` (`id`, `module_id`, `product_id`, `topic`, `price_THB`, `net_THB`, `price_USD`, `net_USD`, `weight`, `stock`) VALUES ('0','10','11','Yellow 1116','790','590','0','0','0','-1');
INSERT INTO `{prefix}_product_additional` (`id`, `module_id`, `product_id`, `topic`, `price_THB`, `net_THB`, `price_USD`, `net_USD`, `weight`, `stock`) VALUES ('0','10','12','Black 58','790','590','0','0','0','-1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('11','4','1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('12','4','1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('13','2','1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('14','2','2');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('15','3','0');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('16','2','2');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('17','4','2');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('18','2','3');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('19','2','1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('20','1','1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('111','2','1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('112','2','1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('113','1','1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('114','2','2');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('115','2','2');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('116','2','2');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('117','2','2');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('118','2','2');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('119','2','1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('120','2','1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('121','4','0');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('122','4','0');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('123','2','2');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('124','2','2');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('125','2','2');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('126','6','3');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('127','3','0');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('128','3','0');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('129','2','3');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('130','4','1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('131','6','2');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('132','2','4');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('133','2','3');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('134','2','1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('135','2','1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('136','2','1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('137','3','0');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('138','3','0');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('139','3','0');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('140','3','0');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('141','3','0');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('142','2','2');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('143','4','1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('144','5','0');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('145','5','0');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('146','5','0');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('147','6','1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('148','3','0');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('149','6','1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('150','4','1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('151','3','0');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('152','2','1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('153','2','1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('154','1','1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('155','2','1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('156','2','2');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('157','2','1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('158','2','1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('159','6','3');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('160','6','3');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('161','2','2');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('149','2','1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('160','2','1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('159','2','2');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('148','6','1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('147','2','2');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('137','6','2');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('136','6','2');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('135','6','2');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('134','6','2');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('133','6','2');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('132','6','2');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('131','2','2');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('130','6','3');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('129','6','3');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('128','6','3');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('127','6','3');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('126','2','2');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('162','2','2');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('163','2','2');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('164','2','4');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('165','2','4');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('166','2','2');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('167','2','2');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('168','2','3');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('169','2','1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('170','2','2');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('171','2','1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('172','2','1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('173','4','2');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('174','4','2');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('175','2','1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('176','2','1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('177','2','1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('178','2','1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('179','4','2');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('1','2','2');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('2','2','2');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('3','2','2');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('4','2','2');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('5','1','1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('6','1','1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('7','1','1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('8','1','1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('9','4','1');
INSERT INTO `{prefix}_product_category` (`id`, `category_id`, `subcategory`) VALUES ('10','4','1');
INSERT INTO `{prefix}_product_detail` (`id`, `language`, `topic`, `keywords`, `description`, `detail`) VALUES ('1','','Off The Shoulder Sheath Dress','Off The Shoulder Sheath Dress','A sleek party dress that satisfies your trendsetting side with an off the shoulder neckline The stretch fit and silky lining team up to keep you lo','A sleek party dress that satisfies your trendsetting side with an off-the-shoulder neckline. The stretch fit and silky lining team up to keep you looking and feeling great well into the evening.');
INSERT INTO `{prefix}_product_detail` (`id`, `language`, `topic`, `keywords`, `description`, `detail`) VALUES ('2','','Solid Off The Shoulder Ruffle Fit And Flare Dress','Solid Off The Shoulder Ruffle Fit And Flare Dress','Make your entrance in this chic fit and flare dress that features a sexy mini length, soft fabric and feminine ruffle accents Pair with sandals or ..','Make your entrance in this chic fit and flare dress that features a sexy mini length, soft fabric and feminine ruffle accents. Pair with sandals or sneakers to turn heads all day long.');
INSERT INTO `{prefix}_product_detail` (`id`, `language`, `topic`, `keywords`, `description`, `detail`) VALUES ('3','','Off The Shoulder Smocked Eyelet Mini Dress','Off The Shoulder Smocked Eyelet Mini Dress','Pure cotton, eyelet accents and a sexy off the shoulder neckline make this dress a must have on warm days Finished with a mini length and ruffles f','Pure cotton, eyelet accents and a sexy off-the-shoulder neckline make this dress a must-have on warm days. Finished with a mini length and ruffles for an extra pop of personality.');
INSERT INTO `{prefix}_product_detail` (`id`, `language`, `topic`, `keywords`, `description`, `detail`) VALUES ('4','','Off The Shoulder Floral Embroidered Shift Dress','Off The Shoulder Floral Embroidered Shift Dress','The easy fit and drop waist of this shift dress say casual, while bright embroidery, smooth fabric and cinched sleeves add a polished finish Wear t..','The easy fit and drop waist of this shift dress say "casual," while bright embroidery, smooth fabric and cinched sleeves add a polished finish. Wear this one for an effortlessly sophisticated desk to drinks outfit.');
INSERT INTO `{prefix}_product_detail` (`id`, `language`, `topic`, `keywords`, `description`, `detail`) VALUES ('5','','Ikat Print Crew Neck Tee','Ikat Print Crew Neck Tee','A must have for every guy #39;s closet, this crew neck printed tee keeps you cool and comfortable','A must-have for every guy&#39;s closet, this crew neck printed tee keeps you cool and comfortable.');
INSERT INTO `{prefix}_product_detail` (`id`, `language`, `topic`, `keywords`, `description`, `detail`) VALUES ('6','','Jersey Scoop Neck Pocket Tank','Jersey Scoop Neck Pocket Tank','A sleeveless tank that s warm weather ready Soft and easy fitting, wear it with your favorite shorts for ultimate casual comfort','A sleeveless tank that\'s warm weather-ready. Soft and easy-fitting, wear it with your favorite shorts for ultimate casual comfort.\r\n\r\n');
INSERT INTO `{prefix}_product_detail` (`id`, `language`, `topic`, `keywords`, `description`, `detail`) VALUES ('7','','Slim Charcoal Gray Check Stretch Wool-Blend Suit Vest','Slim Charcoal Gray Check Stretch Wool Blend Suit Vest','The sharp, modern lines of the five button vest refine any look Pair with our matching jacket and pant for a complete suit, let it refine our crisp..','The sharp, modern lines of the five-button vest refine any look. Pair with our matching jacket and pant for a complete suit, let it refine our crisp 1MX shirts, or use it casually to dress up a graphic tee and jeans.');
INSERT INTO `{prefix}_product_detail` (`id`, `language`, `topic`, `keywords`, `description`, `detail`) VALUES ('8','','Color Block Crew Neck Tee','Color Block Crew Neck Tee','Get a put together casual look with this soft, color blocked short sleeve tee made from a must get stretch cotton blend It s a classic look that s ..','Get a put-together casual look with this soft, color blocked short sleeve tee made from a must-get stretch cotton blend. It\'s a classic look that\'s all-day comfortable.');
INSERT INTO `{prefix}_product_detail` (`id`, `language`, `topic`, `keywords`, `description`, `detail`) VALUES ('9','','Color Block Raglan Henley Sweater','Color Block Raglan Henley Sweater','With soft, pure cotton and a marled, color blocked knit, this henley sweater will be your best friend on brisk days Layer it over classic denim for..','With soft, pure cotton and a marled, color blocked knit, this henley sweater will be your best friend on brisk days. Layer it over classic denim for an ultimate casual-cool and comfortable look. It\'s that easy.');
INSERT INTO `{prefix}_product_detail` (`id`, `language`, `topic`, `keywords`, `description`, `detail`) VALUES ('10','','Striped Notch Neck Henley','Striped Notch Neck Henley','A classically comfortable henley amped up with a notch neckline Pair with denim or chinos for a handsome daily look','A classically comfortable henley amped up with a notch neckline. Pair with denim or chinos for a handsome daily look.');
INSERT INTO `{prefix}_product_detail` (`id`, `language`, `topic`, `keywords`, `description`, `detail`) VALUES ('11','','Merino Wool Blend Thermal Regulating V-Neck Sweater','Merino Wool Blend Thermal Regulating V Neck Sweater','A soft, sophisticated sweater that keeps you warm without sacrificing style The rich Merino wool blend feels luxurious, while a classic v neck makes','A soft, sophisticated sweater that keeps you warm without sacrificing style. The rich Merino wool blend feels luxurious, while a classic v-neck makes it timeless. Layer with a dress shirt for an office-ready look.');
INSERT INTO `{prefix}_product_detail` (`id`, `language`, `topic`, `keywords`, `description`, `detail`) VALUES ('12','','Marled Funnel Neck Pullover Sweater','Marled Funnel Neck Pullover Sweater','Step up your layering game with this sharp funnel neck sweater done in a comfortable, stylish marled knit Matching drawstrings help put an athletic','Step up your layering game with this sharp funnel neck sweater done in a comfortable, stylish marled knit. Matching drawstrings help put an athletic spin on the look.');
INSERT INTO `{prefix}_product_image` (`id`, `product_id`, `thumbnail`, `image`) VALUES ('1','1','thumb-1-1.jpg','1-1.jpg');
INSERT INTO `{prefix}_product_image` (`id`, `product_id`, `thumbnail`, `image`) VALUES ('0','1','thumb-1-0.jpg','1-0.jpg');
INSERT INTO `{prefix}_product_image` (`id`, `product_id`, `thumbnail`, `image`) VALUES ('0','2','thumb-2-0.jpg','2-0.jpg');
INSERT INTO `{prefix}_product_image` (`id`, `product_id`, `thumbnail`, `image`) VALUES ('1','2','thumb-2-1.jpg','2-1.jpg');
INSERT INTO `{prefix}_product_image` (`id`, `product_id`, `thumbnail`, `image`) VALUES ('0','3','thumb-3-0.jpg','3-0.jpg');
INSERT INTO `{prefix}_product_image` (`id`, `product_id`, `thumbnail`, `image`) VALUES ('1','3','thumb-3-1.jpg','3-1.jpg');
INSERT INTO `{prefix}_product_image` (`id`, `product_id`, `thumbnail`, `image`) VALUES ('0','4','thumb-4-0.jpg','4-0.jpg');
INSERT INTO `{prefix}_product_image` (`id`, `product_id`, `thumbnail`, `image`) VALUES ('1','4','thumb-4-1.jpg','4-1.jpg');
INSERT INTO `{prefix}_product_image` (`id`, `product_id`, `thumbnail`, `image`) VALUES ('0','5','thumb-5-0.jpg','5-0.jpg');
INSERT INTO `{prefix}_product_image` (`id`, `product_id`, `thumbnail`, `image`) VALUES ('1','5','thumb-5-1.jpg','5-1.jpg');
INSERT INTO `{prefix}_product_image` (`id`, `product_id`, `thumbnail`, `image`) VALUES ('0','6','thumb-6-0.jpg','6-0.jpg');
INSERT INTO `{prefix}_product_image` (`id`, `product_id`, `thumbnail`, `image`) VALUES ('1','6','thumb-6-1.jpg','6-1.jpg');
INSERT INTO `{prefix}_product_image` (`id`, `product_id`, `thumbnail`, `image`) VALUES ('0','7','thumb-7-0.jpg','7-0.jpg');
INSERT INTO `{prefix}_product_image` (`id`, `product_id`, `thumbnail`, `image`) VALUES ('1','7','thumb-7-1.jpg','7-1.jpg');
INSERT INTO `{prefix}_product_image` (`id`, `product_id`, `thumbnail`, `image`) VALUES ('0','8','thumb-8-0.jpg','8-0.jpg');
INSERT INTO `{prefix}_product_image` (`id`, `product_id`, `thumbnail`, `image`) VALUES ('1','8','thumb-8-1.jpg','8-1.jpg');
INSERT INTO `{prefix}_product_image` (`id`, `product_id`, `thumbnail`, `image`) VALUES ('0','9','thumb-9-0.jpg','9-0.jpg');
INSERT INTO `{prefix}_product_image` (`id`, `product_id`, `thumbnail`, `image`) VALUES ('1','9','thumb-9-1.jpg','9-1.jpg');
INSERT INTO `{prefix}_product_image` (`id`, `product_id`, `thumbnail`, `image`) VALUES ('2','9','thumb-9-2.jpg','9-2.jpg');
INSERT INTO `{prefix}_product_image` (`id`, `product_id`, `thumbnail`, `image`) VALUES ('0','10','thumb-10-0.jpg','10-0.jpg');
INSERT INTO `{prefix}_product_image` (`id`, `product_id`, `thumbnail`, `image`) VALUES ('1','10','thumb-10-1.jpg','10-1.jpg');
INSERT INTO `{prefix}_product_image` (`id`, `product_id`, `thumbnail`, `image`) VALUES ('2','10','thumb-10-2.jpg','10-2.jpg');
INSERT INTO `{prefix}_product_image` (`id`, `product_id`, `thumbnail`, `image`) VALUES ('0','11','thumb-11-0.jpg','11-0.jpg');
INSERT INTO `{prefix}_product_image` (`id`, `product_id`, `thumbnail`, `image`) VALUES ('1','11','thumb-11-1.jpg','11-1.jpg');
INSERT INTO `{prefix}_product_image` (`id`, `product_id`, `thumbnail`, `image`) VALUES ('0','12','thumb-12-0.jpg','12-0.jpg');
INSERT INTO `{prefix}_product_image` (`id`, `product_id`, `thumbnail`, `image`) VALUES ('1','12','thumb-12-1.jpg','12-1.jpg');